- name: PAM password policies (Debian/Ubuntu)
  lineinfile:
    path: /etc/pam.d/common-password
    regexp: '^password\s+requisite\s+pam_pwquality.so'
    line: 'password requisite pam_pwquality.so retry=3 minlen=12 ucredit=-1 lcredit=-1 dcredit=-1 ocredit=-1 enforce_for_root'
  when: ansible_facts['os_family'] == 'Debian'

- name: Configure pwquality (RHEL family)
  copy:
    dest: /etc/security/pwquality.conf
    content: |
      minlen = 12
      dcredit = -1
      ucredit = -1
      lcredit = -1
      ocredit = -1
      retry = 3
  when: ansible_os_family == "RedHat"

- name: PAM password policies (SuSE family)
  lineinfile:
    path: /etc/pam.d/common-password
    regexp: '^password\s+requisite\s+pam_pwquality.so'
    line: 'password requisite pam_pwquality.so retry=3 minlen=12 ucredit=-1 lcredit=-1 dcredit=-1 ocredit=-1 enforce_for_root'
  when: ansible_facts['os_family'] == 'Suse'

