- name: Ensure groups exists
  group:
    name: "{{ item.name }}"
    state: present
  loop: "{{ ssh_users }}"
  when: item.create_user | default(true)

- name: Create users
  user:
    name: "{{ item.name }}"
    group: "{{ item.name }}"
    state: present
    create_home: yes
    shell: /bin/bash
  loop: "{{ ssh_users }}"
  when: item.create_user | default(true)

- name: Ensure local key directory exists
  delegate_to: localhost
  file:
    path: "/home/ansible/.ssh"
    state: directory
    mode: '0700'
  run_once: true

- name: Generate SSH key pairs for users
  delegate_to: localhost
  openssh_keypair:
    path: "/home/ansible/.ssh/{{ item.name }}"
    type: rsa
    size: 2048
    force: false
  loop: "{{ ssh_users }}"
  run_once: true

- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name}}"
    group: "{{ item.name }}"
    mode: '0700'
  loop: "{{ ssh_users }}" 
  when: item.create_user | default(true)

- name: Install authorized keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', '/home/ansible/.ssh/' + item.name + '.pub') }}"
    state: present
  loop: "{{ ssh_users }}"
  when: item.create_user | default(true)

- name: fix authorized_keys permissions
  file:
    path: "/home/{{ item.name }}/.ssh/authorized_keys"
    owner: "{{ item.name }}"
    mode: '0600'
  loop: "{{ ssh_users }}"
  when: item.create_user | default(true)

- name: disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: reload ssh